#ifndef SPECIAL_FUNCTIONS_DETAIL_BELL_POLYNOMIAL_B_H
#define SPECIAL_FUNCTIONS_DETAIL_BELL_POLYNOMIAL_B_H

namespace special_functions::detail {}

#endif // SPECIAL_FUNCTIONS_DETAIL_BELL_POLYNOMIAL_B_H
