#ifndef SPECIAL_FUNCTIONS_DETAIL_HERMITE_POLYNOMIAL_HE_H
#define SPECIAL_FUNCTIONS_DETAIL_HERMITE_POLYNOMIAL_HE_H

#include "hermite_polynomial_he_t.h"

namespace detail {}

#endif // SPECIAL_FUNCTIONS_DETAIL_HERMITE_POLYNOMIAL_HE_H
