#ifndef SPECIAL_FUNCTIONS_DETAIL_RADIAL_POLYNOMIAL_R_H
#define SPECIAL_FUNCTIONS_DETAIL_RADIAL_POLYNOMIAL_R_H

namespace special_functions::detail {}

#endif // SPECIAL_FUNCTIONS_DETAIL_RADIAL_POLYNOMIAL_R_H
