#ifndef SPECIAL_FUNCTIONS_DETAIL_SPHERICAL_BESSEL_Y_H
#define SPECIAL_FUNCTIONS_DETAIL_SPHERICAL_BESSEL_Y_H

namespace special_functions::detail {}

#endif // SPECIAL_FUNCTIONS_DETAIL_SPHERICAL_BESSEL_Y_H
