#ifndef SPECIAL_FUNCTIONS_DETAIL_STIRLING_NUMBER_S_1_H
#define SPECIAL_FUNCTIONS_DETAIL_STIRLING_NUMBER_S_1_H

namespace special_functions::detail {}

#endif // SPECIAL_FUNCTIONS_DETAIL_STIRLING_NUMBER_S_1_H
