#ifndef SPECIAL_FUNCTIONS_DETAIL_STIRLING_NUMBER_S_2_H
#define SPECIAL_FUNCTIONS_DETAIL_STIRLING_NUMBER_S_2_H

namespace special_functions::detail {}

#endif // SPECIAL_FUNCTIONS_DETAIL_STIRLING_NUMBER_S_2_H
