#ifndef SPECIAL_FUNCTIONS_CONFLUENT_HYPERGEOMETRIC_0_F_1_H
#define SPECIAL_FUNCTIONS_CONFLUENT_HYPERGEOMETRIC_0_F_1_H

#include <special_functions/detail/

namespace special_functions {

}

#endif // SPECIAL_FUNCTIONS_CONFLUENT_HYPERGEOMETRIC_0_F_1_H
