#ifndef SPECIAL_FUNCTIONS_EXPONENTIAL_INTEGRAL_E1_H
#define SPECIAL_FUNCTIONS_EXPONENTIAL_INTEGRAL_E1_H


#include <complex>


namespace special_functions {

}

#endif // SPECIAL_FUNCTIONS_EXPONENTIAL_INTEGRAL_E1_H
