#ifndef SPECIAL_FUNCTIONS_GAUSS_HYPERGEOMETRIC_2_F_1_H
#define SPECIAL_FUNCTIONS_GAUSS_HYPERGEOMETRIC_2_F_1_H

namespace special_functions {

}

#endif // SPECIAL_FUNCTIONS_GAUSS_HYPERGEOMETRIC_2_F_1_H
