#ifndef SPECIAL_FUNCTIONS_LAGUERRE_POLYNOMIAL_L_H
#define SPECIAL_FUNCTIONS_LAGUERRE_POLYNOMIAL_L_H


#include <complex>


namespace special_functions {

}

#endif // SPECIAL_FUNCTIONS_LAGUERRE_POLYNOMIAL_L_H
